apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: busybox
        image: busybox
        command:
        - sh
        - -c
        - "trap \"exit 0\" SIGTERM; while true; do echo $(hostname) $(date); sleep 1; done"
